<template>
  <Navbar />
  <main>
    <div class="about-main-content">
      <div class="about-main-content-grid">
        <h1>My Story</h1>
        <div class="about-img-container">
          <img
            src="https://lh3.googleusercontent.com/drive-viewer/AEYmBYQRM-jWXBbATi2bFVsXTDTTB8rJjSl8KP-673nkhfR8aN_MyCgCjpeStmvMMuYl3o_NCySD3svXBosCnHEnIBCE4bT-9A=s1600"
            alt=""
          />
        </div>
        <div class="about-content-container">
          <h2>I am Seth Tobias</h2>
          <p>
            I am a 19-year-old aspiring Full-stack Web Developer. My journey
            started in 2020 when I first came across coding. I started with the
            fundamentals of HTML. I however abruptly stopped as my academics at
            the time were more important to me. I picked up where I left off
            earlier this year, as I matriculated in 2022 I found myself having a
            lot more free time. Through my efforts, I managed to have a basic
            understanding of HTML and CSS. In the meantime, while I was doing my
            studies I scoured the internet for courses on Web Development.
            Thanks to this I now find myself a part of the Life Choices Coding
            Academy. My journey in learning Web Development started at this
            point. I now find myself being able to create my very own Vue.js
            Portfolio.
          </p>
        </div>
        <div class="image-map-container">
          <div class="image-map-text">
            <h2>My Hobbies:</h2>
            <p>
              Bellow is an image map containing a few of my favourite hobbies to
              do in my free time. Consisting of Reading, watching Movies, Sport
              and listening to Music. Simply click the relevant item in the
              image to learn more!
            </p>
          </div>
          <div class="image-maps">
            <div class="image-map-desktop">
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img
                src="https://lh3.googleusercontent.com/drive-viewer/AEYmBYSGtOQMI0a4bHB8PHScSiaQ0XFs61wA_hZwvq77ejGjAQO-XmVqluG9JILysFAe_5Hh95NJYyXUgwZHsU7D7dtqaBnBJg=s1600"
                usemap="#image-map"
              />

              <map name="image-map">
                <router-link to="/music">
                  <area
                    target=""
                    alt="music"
                    title="music"
                    coords="181,232,77,94"
                    shape="rect"
                  />
                </router-link>
                <router-link to="/movies">
                  <area
                    target=""
                    alt="movies"
                    title="movies"
                    coords="248,17,624,22,620,226,652,227,628,265,245,256,187,225,196,213,232,211"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/sport">
                  <area
                    target=""
                    alt="hockey"
                    title="hockey"
                    coords="899,49,919,56,926,76,297,718,402,777,388,805,187,866,142,944,91,952,29,817,38,592,53,568,99,571,137,591,152,674,232,692,237,578,248,542,284,526,318,537,332,568,349,580"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/reading">
                  <area
                    target=""
                    alt="reading"
                    title="reading"
                    coords="764,409,941,461,884,731,695,665"
                    shape="poly"
                  />
                </router-link>
              </map>
            </div>
            <div class="image-map-ipad">
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img
                src="https://lh3.googleusercontent.com/drive-viewer/AEYmBYSoQxi-3rCO739ECU3lSpHFdCqtfRowGUKgMEpT3q0RJtAg2F3H4ciL1I4stmbtljdVxYhTShFgi_S52j2GRH0jTW-hmg=s2560"
                usemap="#image-map"
              />

              <map name="image-map">
                <router-link to="/music">
                  <area
                    target=""
                    alt="music"
                    title="music"
                    coords="54,65,120,159"
                    shape="rect"
                  />
                </router-link>
                <router-link to="/movies">
                  <area
                    target=""
                    alt="movies"
                    title="movies"
                    coords="171,10,424,15,424,153,450,156,424,182,167,174,124,158,123,147,157,147"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/sport">
                  <area
                    target=""
                    alt="hockey"
                    title="hockey"
                    coords="614,36,630,34,638,52,206,488,271,524,278,547,194,574,122,598,102,651,60,649,21,571,26,408,39,389,84,392,101,421,102,463,160,472,171,415,162,391,179,363,210,360,228,382,225,413"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/reading">
                  <area
                    target=""
                    alt="reading"
                    title="reading"
                    coords="522,279,474,454,606,503,648,316"
                    shape="poly"
                  />
                </router-link>
              </map>
            </div>
            <div class="image-map-mid">
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img
                src="https://lh3.googleusercontent.com/drive-viewer/AEYmBYSiI8zOi3tAOt4vHdBAIjlHpAvChkHwUqk0bkIBc5mzSRdmP4paKsXzVMJEB5E_LT_qwQAFpvFyJmPs0aQzu9XlHedWhA=s2560"
                usemap="#image-map"
              />

              <map name="image-map">
                <router-link to="/music">
                  <area
                    target=""
                    alt="music"
                    title="music"
                    coords="26,29,54,73"
                    shape="rect"
                  />
                </router-link>
                <router-link to="/movies">
                  <area
                    target=""
                    alt="movies"
                    title="movies"
                    coords="55,65,73,66,77,5,196,6,195,69,208,71,196,82,85,80,61,75"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/sport">
                  <area
                    target=""
                    alt="hockey"
                    title="hockey"
                    coords="28,176,42,187,47,213,71,219,83,205,75,177,85,163,99,167,106,185,283,15,291,16,294,24,95,224,125,244,121,253,55,273,43,298,28,297,10,252,10,191,14,179"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/reading">
                  <area
                    target=""
                    alt="reading"
                    title="reading"
                    coords="218,207,241,127,296,145,277,229"
                    shape="poly"
                  />
                </router-link>
              </map>
            </div>
            <div class="image-map-mobile">
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img
                src="https://lh3.googleusercontent.com/drive-viewer/AEYmBYRIrudgbyHT7nzv5Rhg2izMAXbuwVPsF_G0HCjRSaDsuARnpqH8Y9AD2yVcLUkMCmPULxZjmWI9DNJilUPwhT-SUgwR=s2560"
                usemap="#image-map"
              />

              <map name="image-map">
                <router-link to="/music">
                  <area
                    target=""
                    alt="music"
                    title="music"
                    coords="25,26,53,69"
                    shape="rect"
                  />
                </router-link>
                <router-link to="/movies">
                  <area
                    target=""
                    alt="movies"
                    title="movies"
                    coords="122,5,181,6,181,63,196,66,182,76,73,75,54,67,69,59,69,33,71,3"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/sport">
                  <area
                    target=""
                    alt="hockey"
                    title="hockey"
                    coords="19,166,36,171,44,197,65,204,77,189,68,164,80,155,93,159,101,175,264,13,270,14,273,19,90,211,118,231,113,238,52,253,41,274,24,279,7,237,9,178"
                    shape="poly"
                  />
                </router-link>
                <router-link to="/reading">
                  <area
                    target=""
                    alt="reading"
                    title="reading"
                    coords="221,117,202,195,261,216,278,135"
                    shape="poly"
                  />
                </router-link>
              </map>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <Footer />
</template>

<script>
import Navbar from "../components/Navbar.vue";
import Footer from "../components/Footer.vue";

export default {
  name: "AboutView",
  components: {
    Navbar,
    Footer,
  },
};
</script>

<style scoped>
:root {
  --text: #002e28;
  --background: #e0fffa;
  --primary: #008a70;
  --secondary: #5cd1ff;
  --accent: #007cf0;
}

.about-main-content {
  margin-top: 50px;
  margin: 0 auto;
  margin-top: 50px;
  width: 1200px;
}

.about-main-content-grid {
  width: 80%;
  margin: 0 auto;
  display: grid;
  grid: 100px max-content 1fr / 1fr 2fr;
  gap: 0px 15px;
}

h1 {
  text-align: center;
  grid-area: 1/1/1/3;
  font-size: 2.75rem;
}

.about-img-container {
  grid-area: 2/1/2/1;
}

.about-img-container img {
  height: 600px;
  border: 3px solid var(--primary);
}

.about-content-container {
  grid-area: 2/2/2/3;
  text-align: right;
}

.about-content-container h2 {
  font-size: 2rem;
  line-height: 0px;
}

.about-content-container p {
  font-size: 1.8rem;
  line-height: 1.7rem;
}

.image-map-container {
  margin: auto;
  grid-area: 3/1/3/4;
  display: flex;
  flex-flow: row wrap;
  align-content: center;
  justify-content: center;
}

.image-map-text h2 {
  text-align: center;
  font-size: 3rem;
}

.image-map-text p {
  text-align: center;
  font-size: 1.9rem;
}

.image-map-container img {
  border: 10px ridge var(--text);
}

.image-map-ipad {
  display: none;
}

.image-map-mid {
  display: none;
}
.image-map-mobile {
  display: none;
}

@media screen and (width < 300px) {
  .image-map-mobile {
    display: block;
  }
  .image-map-mid {
    display: none;
  }
  .image-map-ipad {
    display: none;
  }
  .image-map-desktop {
    display: none;
  }
}

@media screen and (299px < width < 730px) {
  .image-map-mobile {
    display: none;
  }
  .image-map-mid {
    display: block;
  }
  .image-map-ipad {
    display: none;
  }
  .image-map-desktop {
    display: none;
  }
}

@media screen and (730px < width < 1100px) {
  .image-map-mobile {
    display: none;
  }
  .image-map-mid {
    display: none;
  }
  .image-map-ipad {
    display: block;
  }
  .image-map-desktop {
    display: none;
  }
}

@media screen and (width > 1100px) {
  .image-map-mobile {
    display: none;
  }
  .image-map-mid {
    display: none;
  }
  .image-map-ipad {
    display: none;
  }
  .image-map-desktop {
    display: block;
  }
}
</style>
